### ISSUE TITLE
Add a "High Scores" Screen

### ISSUE THREAD

**Issue by drewtaylors** [UCSB-CS56-Projects/cs56-games-simon-says#27]
It would be nice to have a High Score screen which reports the highest score earned in each level that remains static even when the game is exited.

- Added code to write highest score into a separate file for each level
- Added a new screen with main menu button. New screen pulls data from txt files to display static high scores for each level

(requesting ~250 points)

**Comment by drewtaylors** [comment]
269d86cbbb7c18e5a7203add5054b499e2bc299b

**Comment by hannavigil** [comment]
Approved
