### ISSUE TITLE
"Flash" Sometimes Not Occuring

### ISSUE THREAD

**Issue by drewtaylors** [ucsb-cs56-projects/cs56-games-simon-says#30]
Clicking too fast or not constantly interacting with the JFrame can sometimes cause it to skip flashes. We believe this is an issue with the thread.sleep() function and the logic behind it used in the code. This issue is not always consistent. Sometimes the game works just fine so this could also just be an issue with JFrame and the application we are using to run the game. (200 pts.)

**Comment by hannavigil** [comment]
W16 OK

**Comment by JohnUCSB** [comment]
F16 Approved  - 200 pts
