### ISSUE TITLE
Non-Editable Instructions

### ISSUE THREAD

**Issue by drewtaylors** [UCSB-CS56-Projects/cs56-games-simon-says#31]
Using a textArea for the instructions allows the text to be editable. Making this text permanent would be a nice addition (50 pts.)

**Comment by hannavigil** [comment]
W16 OK

**Comment by JohnUCSB** [comment]
F16 Approved  - 50 pts

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-simon-says/commit/e83a66fb4136b4fd8c8286f331fd05aae8b7048d
