### ISSUE TITLE
Customizable Images for Buttons

### ISSUE THREAD

**Issue by drewtaylors** [ucsb-cs56-projects/cs56-games-simon-says#32]
We think it would be cool to create customizable images for the buttons. Potentially ones the user could upload on their own through the game. Otherwise it would be cool to have images other than just the plain colors. (150 pts.)

**Comment by hannavigil** [comment]
W16 OK

**Comment by JohnUCSB** [comment]
F16 Approved  - 150 pts

**Comment by angel90650** [comment]
This requires:
adding image assets for each color button, and pressed buttons
updating simonButton class to set image and set color
updating each simonFlash class since each assumes the color is determined by button background color.
