### ISSUE TITLE
Rules presented in a better fashion 

### ISSUE THREAD

**Issue by hechttrevor** [UCSB-CS56-Projects/cs56-games-simon-says#39]
Instead of having the rules consist of 11 bullet points, the rules could be presented with a small number of slides that have more visual representations along a with short descriptions of what is going on.  The user should be able to iterate forwards or backwards through the slides.  

150 points

**Comment by JohnUCSB** [comment]
F16 OK (150 pts)

**Comment by hechttrevor** [comment]
After doing work and finishing this issue I believe we should receive more than 150 points of credit. Fixing this issue not only require rewriting an entire class, but it also involved creating 9 different jpg files that were used as the slides.  I believe 250 points would be fair.

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-simon-says/pull/55
