### ISSUE TITLE
Remove box around the text in the buttons

### ISSUE THREAD

**Issue by hechttrevor** [UCSB-CS56-Projects/cs56-games-simon-says#40]
When you hold down your cursor over any button, a box appears around the text of the button. This looks unintentional and would look better without it. 

50 points

**Comment by JohnUCSB** [comment]
F16 OK (50 pts)

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-simon-says/pull/50
