### ISSUE TITLE
Change the background 

### ISSUE THREAD

**Issue by hechttrevor** [UCSB-CS56-Projects/cs56-games-simon-says#43]
A plain black background is a bit dull, liven it up with a more inviting and colorful background. 

50 points

**Comment by JohnUCSB** [comment]
F16 OK (50 pts)

**Comment by hechttrevor** [comment]
Changes have been updated.

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-simon-says/pull/55
