### ISSUE TITLE
Add a time limit for rounds

### ISSUE THREAD

**Issue by chetkoziol** [UCSB-CS56-Projects/cs56-games-simon-says#44]
Right now you can take as long as you want to repeat the pattern after the game finishes making it. I think there should be a time limit (maybe only on the hardest difficulty) on how long you can take to input the pattern. (150 points)

**Comment by JohnUCSB** [comment]
F16 OK (150 pts)

**Comment by chetkoziol** [comment]
I think this issue should be worth 250 points. There was a lot of work involved having to get a timer for each round, including when to take a life off, when to stop the timer/thread, when to start a new timer for the round, the logic in multiple functions to check if the round should be over/timer should end, and keeping track of and coordinating information between multiple threads. I think if the game were designed better originally it might have been easier to add a level timer, but with the way I received the code it took a very substantial amount of time to achieve this.

**Comment by JohnUCSB** [comment]
F16 OK (250 pts)

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-simon-says/pull/50
