### ISSUE TITLE
Intermediate Level Glitch 

### ISSUE THREAD

**Issue by hechttrevor** [UCSB-CS56-Projects/cs56-games-simon-says#51]
When simulating the SimonInterL class, there is a glitch that allows you to continue to press the start button at any point in this game.  This causes the game to reset or even start to glitch out.  

100 points

**Comment by JohnUCSB** [comment]
F16 OK (100 pts)

**Comment by hechttrevor** [comment]
changes have been updated

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-simon-says/pull/55
