### ISSUE TITLE
Confusing name of Amateur Classes 

### ISSUE THREAD

**Issue by hechttrevor** [UCSB-CS56-Projects/cs56-games-simon-says#52]
The flash and frame class for the amateur level are called SimonFlash and SimonFrame, which does not specify that they are in fact for amateur.  Their class name should have Amateur in it do be constant with the Pro and Inter classes. 

50 points

**Comment by JohnUCSB** [comment]
F16 OK (50 pts)

**Comment by hechttrevor** [comment]
changes have been updated

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-games-simon-says/pull/55
