### ISSUE TITLE
Exiting during game causes delayed gameover screen

### ISSUE THREAD

**Issue by angel90650** [UCSB-CS56-Projects/cs56-games-simon-says#64]
If a game is exited before it is lost, then a game over window will open after 30 to 60 seconds of waiting in the main menu.

**Comment by joelbagan** [comment]
Cannot replicate bug. Add detailed instructions on how to replicate.

**Comment by angel90650** [comment]
1. start a new game(Professional)
2. press start
3  close after the  4 seconds 
4. wait for 30 seconds while in the main menu and a game over screen will pop up

This is happening because the professional level of the game is actually timed, this is not described in the project or in the rules of the game, so all of that will need to get updated as well. when the game is exited, the timer does not stop. The timer goes for 13 seconds and then takes away a life until there are no lives left and a game over screen is shown.

**Comment by joelbagan** [comment]
F17 OK (100pts)

**Comment by joelbagan** [comment]
Resolved in https://github.com/UCSB-CS56-Projects/cs56-games-simon-says/pull/70
